x-common-service-settings: &common-service-settings
  build:
    context: .
    dockerfile: Dockerfile
  image: starcraft-vision:dev
  volumes:
    - ./data:/workspace/data
    - ./src:/workspace/src
  user: "${UID}:${GID}"
  working_dir: /workspace
  stdin_open: true
  tty: true

services:
  preprocess_input:
    <<: *common-service-settings
    entrypoint: ["bash", "src/entrypoints/preprocess_input.sh"]
    command: []

  preprocess_label:
    <<: *common-service-settings
    entrypoint: ["bash", "src/entrypoints/preprocess_label.sh"]
    command: []

  preprocess_pair:
    <<: *common-service-settings
    entrypoint: ["bash", "src/entrypoints/preprocess_pair.sh"]
    command: []

  train:
    <<: *common-service-settings
    container_name: starcraft-dev
    entrypoint: ["bash", "src/entrypoints/training.sh"]
    command: []
