services:
  dispatcher:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile
    image: starcraft-vision:dev
    environment:
      - PYTHONPATH=/workspace/src
      - TORCH_HOME=/workspace/.torch_cache
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    volumes:
      - ${WANDB_API_KEY}:/run/secrets/wandb_api_key:ro
      - ${SYNOLOGY_CHAT_WEBHOOK_URL}:/run/secrets/synology_chat_webhook_url:ro
      - ${DATA_DIR}:/workspace/data
      - ${SRC_DIR}:/workspace/src
      - ${MODELS_DIR}:/workspace/models
      - ${PREDICTIONS_DIR}:/workspace/predictions
      - ${TORCH_CACHE_DIR}:/workspace/.torch_cache
      - ./entrypoint.sh:/workspace/entrypoint.sh
    user: "${UID}:${GID}"
    shm_size: '4g'
    working_dir: /workspace
    stdin_open: true
    runtime: nvidia
    entrypoint: ["bash", "entrypoint.sh"]