# config.yaml
defaults:
  - dataset: fold1
  - architecture: rtdetr
  - kbrs: enabled
  - kbrs_loss: "kbrs025"
  - _self_ 

use_kbrs: ${kbrs.use_kbrs}
# ===== Data & Replays =====
train_replays: ${dataset.train_replays}
test_replays: ${dataset.test_replays}
include_components: [worker, ground, air, building, vision]
label_method: all_correct
data_root: /workspace/data

# ===== Hyperparameters =====
seed: 123
max_epoch: 1
window_size: 4
interval: 8
batch_size: 8
learning_rate: 0.005
sample_ratio: 1.0

# ===== Validation & Testing =====
val_count: 100
test_eval_every: 0

# ===== Environment & Execution =====
mode: "train_and_inference"
log_level: log
do_inference_after_train: true
cuda: true
num_workers: 1

# ===== Paths =====
prediction_root: /workspace/predictions
model_root: /workspace/models
log_root: /workspace/models
id_string: ""

hydra:
  run:
    dir: /workspace/results/hydra/run/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: /workspace/results/hydra/multirun
    subdir: ${now:%Y%m%d_%H%M%S}_${hydra.job.num}