defaults:
  - dataset: fold1
  - model: vanilla

  - kbrs_loss: kbrs025
  - kbrs_score: base_score
  - _self_          

train_replays: ${dataset.train_replays}
test_replays: ${dataset.test_replays}

include_components: [worker, ground, air, building, vision]
label_method: all_correct
seed: 123
max_epoch: 30
window_size: 4
interval: 8
batch_size: 16
sample_ratio: 1.0
log_level: log
do_inference_after_train: true

learning_rate: 0.005
val_count: 1000
test_eval_every: 0
do_normalize: false
normalize_mean: null
normalize_std: null
resize_mode: resize
min_sizes: [800]
max_size: 1333
rpn_small_anchors: false
cuda: true
num_workers: 32
data_root: /workspace/data
log_root: /workspace/models
id_string: ""

use_kbrs:      ${model.use_kbrs}
loss_weights:  ${model.loss_weights}
kbrs_params:   ${model.kbrs_params}

hydra:
  run:
    # 단일 실행 결과
    dir: /workspace/results/hydra/run/${now:%Y%m%d_%H%M%S}
  sweep:
    # 멀티런 결과
    dir: /workspace/results/hydra/multirun
    subdir: ${now:%Y%m%d_%H%M%S}_${hydra.job.num}